### ISSUE TITLE
build - main - ERROR - Lengths of inputs do not match. Left: 0, Right: 3

### ISSUE THREAD

**Issue by aweerts** [Deltares/hydromt_wflow#115]
error building models related to river width

hydromt build wflow b92eb513-0438-4d57-94c0-c3c0c2c935c1 -r 0.0083333 "{'subbasin': [-96.4458333334093,30.6958333332901], 'strord': 4, 'bounds': [-96.5183333333333,30.6441666666667,-96.3891666666667,30.7766666666667]}" -i wflow_build_1km_vito.ini --dd -vv

**Comment by laurenebouaziz** [comment]
when building a model for a small upstream basin, the rivers_lin2019_v1 dataset is empty. this gives an issue when trying to calculate the nearest distance between river shape and lin dataset in river.py in function river_bathymetry:
idx_nn, dst_nn = gis_utils.nearest(gdf_out, gdf_riv) 
as gdf_riv is empty. 

@hboisgon , have you encountered this issue before?

**Comment by hboisgon** [comment]
Yes but did not really looked into yet. We also have an 'old' method ``setup_riverwidth``. Wonder if in the case lin has no data it may help.

**Comment by DirkEilander** [comment]
to solve this I propose the following:
- set a try-except clause around the get_geodataframe in WflowModel.setup_rivers
- accommodate for gdf_riv=None in hydromt_wflow.workflows.river.river_bathymetry where we can either apply the min_rivwth & min_rivdpth
- ideally, we would fit a power-law equation (e.g. based on the river_lin dataset) to estimate river width and depth for cells where we don't have data instead of the min values.

**Comment by DirkEilander** [comment]
For now a workaround is to leave out "river_geom_fn" in [setup_rivers] and add a the [setup_riverwidth] method after. The latter is the old deprecated method. This communicated this with @aweerts

**Comment by hboisgon** [comment]
Closed as duplicate in #195
