### ISSUE TITLE
Getting invalid band count error while updating the model with freq_out attribute

### ISSUE THREAD

**Issue by abdulrehman565** [Deltares/hydromt_wflow#174]
I was updating my model for a large forcing data using freq_out attribute by following this:
https://deltares.github.io/hydromt_wflow/latest/_examples/update_model_forcing.html

But I am getting invalid band count error.

![Screenshot 2023-04-26 130524](https://user-images.githubusercontent.com/130044572/234511182-72234adb-9b1f-4c4c-9d54-1fbfaf70bcfe.jpg)

How to resolve this?

**Comment by DirkEilander** [comment]
Dear @abdulrehman565, we need more information in order to be able to understand and reproduce your error. Could you please share the HydroMT logfile of the error as well as a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)? From your issue we have no clue what settings you used and are unable to help you.

**Comment by hboisgon** [comment]
No news so closing, please re-open if this is still valid.
