### ISSUE TITLE
Add Soilgrids v0.2 data

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#21]
Update soilgrids workflow to also work with the new version of Soilgrids.

**Comment by hboisgon** [comment]
There is a new version (2.0) of SoilGrids available: https://soilgrids.org/

download global datasets
include in wflow build

Compared to the 2017 version the data is organized a bit different. Average value per layer is provided, instead of a value that is valid for a certain depth.

**Comment by laurenebouaziz** [comment]
Hi @hboisgon and @verseve , I have made changes in the soilgrids2 branch and wanted to explain here more in detail what I did. Could (one of) you please let me know if additional changes are needed?

Steps undertaken to include soilgrids2 (https://www.isric.org/explore/soilgrids/faq-soilgrids) and adapt the workflow:

1. data download of the complete maps in VRT format through WebDAV (projection in Homolosine projection)
https://files.isric.org/soilgrids/latest/data/ and stored on p drive 

Notes on new maps:
- maps of clay, sand, silt and ph have a slightly different extent than bdod and soc:
bdod and soc: shape 58034, 15924**3** and bounds [-19949000.0, -6147500.0, 19861750.0, 8361000.0]
versus other maps 58034, 15924**6** and bounds [-19949750.0, -6147500.0, 19861750.0, 8361000.0]
There seems to be three columns missing in the bdod and soc maps compared to the others.

I contacted Laura Poggio from soilgrids  and she replied: "_we will look into this and try to make them homogeneous as soon as possible. In the meantime, according to your work-flow I can suggest potential solution. The fastest (computationally) would be to use gdal to change the extent of the files to make them the same._ "

- depth to bedrock is lacking in the 2020 version. Laura indicated that they are working on it and that the new maps will become available at the end of this year. She did not reply if she expected large changes for this variable.

- soil taxonomy is also lacking, Laura indicated that they do not plan to provide this map anymore. 

Based on these differences I did the following preprocessing steps:

2. Preprocess 
- clip sand, clay, silt and ph to the extent of soc and bdod (I first tried a gdalwarp, but this did not work)
- soilthickness map -- use the map from 2017 version -- gdalwarp to homolosine projection and extent of other maps and convert to vrt format (but I haven't done this nicely with separate tiles - instead it is just a single tile, this could be improved. My main aim now was to have all files as vrt to read them from the yaml with a similar *_mean.vrt extension.
- taxonomy map -- same procedure as soilthickness map

3. yml file:
I modified the data_sources_deltares.yml file by renaming the old soilgrids to soilgrids_v2017 and added the new soilgrids maps. (keep the old as backup for now). Not sure where this file is stored though in the hydromt repos. I have added this file in the discussion here, can be used with the -d option. 

4. Workflow
The main differences between soilgrids 2017 and 2020 are that before we had 7 maps at specific depth locations. We now have 6 maps for depth intervals instead. In the paper of Sousa et al., 2020 (https://doi.org/10.5194/soil-2020-65), it is mentioned: "_the properties are computed at the mid-point of the interval and are considered constant over the whole depth interval_".

This difference lead to the following changes in the workflow:
- previously thetaS and thetaR were averaged with a trapezoidal function as indicated in the paper of Hengl. Assuming that now the properties are per depth interval, I just applied a simple average function per depth interval (see _average_soillayers_block_ instead of _average_soillayers_)

- to calculate M (or popt), I used the following depths: 0, 10.0, 22.5, 45.0, 80.0, 150.0 These represent the midpoint depths except for the upper one, where I considered the surface at 0cm. Please let me know if this you think this should be adapted.

- the c parameter was previously derived for the soil layers: _10, 40, 120, > 120_. I am not entirely sure why these depths were selected, I thought it should relate to the default layers in sbm which are [0,100], [100,300], [300,800], [800,>] ? Instead I now defined: _c_sl_index = [2, 3, 4, 6]  # matching 100, 225, 450, 1500_  . But let me know if this makes sense. Related to c, is also the issue #22 that I have not looked into yet.

- Additionally, I added a coordinate for the soil layer (sl) in the dataset at the beginning of the script so we don't need to loop over all the layers anymore in the functions.

- I didn't make changes to the sediment part as it is only using the most upper layer. 

- I didn't make changes yet in the interp_na, based on the discussion in #17 

- also I see this could be an opportunity to work on #28 ? 

- I have quickly looked at the differences of the previous and new soilgrids for the Moselle catchment and the new maps seems to be more blurry where previously you could recognize e.g. the part near the river. Also the M parameter seems to be lower than before. I haven't yet run the model with the new maps, but I will do this and also make more detailed comparisons of the maps. But I thought it would be good to hear your feedback already at this point!

Thanks :) 

Here is the yml file for the -d option to read the new soilgrids files:
[data_sources_deltares_soilgrids.zip](https://github.com/Deltares/hydromt_wflow/files/6466864/data_sources_deltares_soilgrids.zip)

**Comment by laurenebouaziz** [comment]
Follow-up changes (commits of June 2nd):

- support both soilgrids (version 2017) and soilgrids_2020 ---- this makes the code rather ugly with if statements, but not sure what is a better solution for now, and I think it is important to keep soilgrids 2017 before we test soilgrids 2020 more in detail? 

- for soilgrids (2017), the code to determine the c parameter is still based on specific depths, no time to script the average over non standard depths with the trapezoidal rule. However, for the 2020 version, the c is based on averages over the wflow_sbm layers.

- wflow_soil is replaced by calculation of soil texture using average values of clay and silt percentages over the soilthickness depth. Not sure if we add this map as "soil_texture" or replace "wflow_soil", now I have replaced wflow_soil. 

- take over changes from main: in ufunc add keep_attrs and interpolate_na("nearest") 

- in data_sources_deltares_soilgrids.yml soilgrids_2020 is added (TODO: remove TAXUSDA) -- attached in the zip below to test the workflow for v2020 

- in wflow build, either indicate for soil_fn 'soilgrids' or 'soilgrids_2020' 

- First results for the soil maps of the moselle: there are large differences in the resulting maps, i.e. for thetaR, more blurry map for 2020 compared to 2017 (location of rivers no longer clearly visible). Also different patterns and magnitudes for other maps. Hard to say if it will lead to an overall improvement, probably improvement at some locations and decrease of performance at other locations. (see attached ppt for differences).

I suggest that Willem @verseve first reviews the adapted code and more specifically if the proposed calculations are ok? 
Then Hélène @hboisgon you can maybe do the final check for hydromt before merging to main?
Does this work for you? 

Thanks!

[Soilgrids 2017 versus 2020.pptx](https://github.com/Deltares/hydromt_wflow/files/6585808/Soilgrids.2017.versus.2020.pptx)

[data_sources_deltares_soilgrids.zip](https://github.com/Deltares/hydromt_wflow/files/6585810/data_sources_deltares_soilgrids.zip)

**Comment by DirkEilander** [comment]
I believe this is implemented in #31 
@laurenebouaziz please reopen if this is still relevant
