### ISSUE TITLE
c parameter from SoilGrids

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#22]
The Brooks-Corey c parameter for wflow_sbm is now directly linked to a soil layer depth of SoilGrids:
for this parameter default z [cm] of soil layers wflow_sbm: 10, 40, 120, > 120
is linked to SoilGrids layers [2,4,6,7] starting at index 1:
soil depth [cm] SoilGrids: [0.0, 5.0, 15.0, 30.0, 60.0, 100.0, 200.0]
an improvement is to use average values for the wflow_sbm soil layers.

**Comment by hboisgon** [comment]
@verseve is still relevant? I think you opened it in the (very) old Gitlab repository of hydromt.
If yes could you set a priority?

**Comment by JoostBuitink** [comment]
I think this is still relevant: currently we assume certain soil layers (10, 40, 120, >120, as mentioned above). It might be nice to allow for user-defined soil layers, and that the `c` parameter is inferred automatically for these depths, instead of the fixed intervals now. This might be a requirement for the water demand functionality, to set to layer with limited conductivity in paddy-regions.

**Comment by JoostBuitink** [comment]
Some updates after a "refinement chat" with @verseve, including what I think would be a nice solution (as we will need this functionality for https://github.com/Deltares/hydromt_wflow/issues/87).

Currently, the code to calculate the `c` parameter assumes fixed soil layers (corresponding to the "default" setting in wflow_sbm of `thicknesslayers = [ 100, 300, 800,]`), see the code below:

https://github.com/Deltares/hydromt_wflow/blob/47cfe4b3d72914e958f81cc7a68ec880682a2c88/hydromt_wflow/workflows/soilgrids.py#L450-L479

To improve the functionality, it would be good if we allow the user to specify their own layers. A new function takes this list of required soil layers and infers the correct `c` values for each layer (preferably as a separate function, explained below), ensure correct weighing from the SoilGrids layers, for both versions). The .toml file also needs to be updated in this function.

For the water demands, we want to update the model with custom layers, to allow for paddy fields to have a layer with limited conductivity, in order to prevent water from easily infiltrating into the ground. Therefore, in this workflow, we would like to update the layers (and hence the `c` parameter) in the case the model does not yet have the required soil layers.

**Comment by hboisgon** [comment]
@JoostBuitink in the case of the water demands, the update of the c paramter is done in a ``setup_paddy`` function or would you prefer to take out ``c`` from ``setup_soilmaps`` and create its own function ``setup_brooks_corey``? With this, you repeat some steps of reading soilgrids and computing thetaS again but might make it more easy for a user to also just update the sbm soil layers without having to recompute all soil parameters?
What do you think?

**Comment by hboisgon** [comment]
Discuss that we will do a separate workflow function for c parameter that can be called from the water demands one later.

One thing that is still not clear while digging @verseve and @JoostBuitink :

- does wflow need c at depth (100, 400, 1200) or averaged over the soil layer(0-100, 100-400, 400-1200)? Seems in the current implementation we give at depth for soilgrids2017 and averaged over the soil layer for soilgrids2020

**Comment by JoostBuitink** [comment]
After a short discussion with @verseve, we decided that averaged over the soil layer is probably the best solution!

**Comment by hboisgon** [comment]
Thanks! I'll implement this then
