### ISSUE TITLE
Implement results and read_results method

### ISSUE THREAD

**Issue by hboisgon** [Deltares/hydromt_wflow#40]
Adding a results object and the corresponding read_results method.

To read the results and know where and what is stored in the output nc and csv file, the corresponding TOML file and settings are needed. This means **one TOML file per wflow run**. The path and names of the files are also read from there.

The results objects would be a dictionnary containing **(edit after comments from Dirk)**:

- **a "output" xr.Dataset** for the gridded netcdf file (output section of the TOML)
- **a "netcdf" xr.Dataset** for the netcdf point timeseries file (neycdf section of the TOML)
- **different GeoDataArrays for the csv file** , one per column (csv section and csv.column sections of the TOML). The xy coordinates are the coordinates of the station or of the centroid of the subcatch/area. The variable name in the GeoDataArray corresponds to the csv header attribute.

**Comment by DirkEilander** [comment]
Good proposal @hboisgon ! We could also start saving results as a dictionary of Datasets and/or DataArrays. I would prefer that over a dictionary with dictionaries of DataArrays. This is closer to how the wflow data is saved and will also make some postprocessing steps easier, e.g.: to do zonal statistics for all variables in a Dataset can be done in one step instead of looping over the DataArrays. This would require a change in the `set_results` and `test_model_api`

**Comment by hboisgon** [comment]
I think a dictionnary of datasets and datarrays is better indeed @DirkEilander !
Would that be a problem for sphincs if I adapt the `set_results` method? 
Or is it better to add an argument to the function that splits the dataset into dataarray if true and keeps the dataset if false?

**Comment by DirkEilander** [comment]
An argument whether to split the Dataset into DataArray sounds good. I think by default it should not split (more intuitive) and keep the Dataset. Will make this work on the SFINCS side after your implementation.

**Comment by hboisgon** [comment]
Update of the set_results method of the model API is done here: https://github.com/Deltares/hydromt/pull/58
